/**
 * 
 */
package mg.alpha.gestion.operations.shared.ui.desktop.outlines.pages.bilan;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class BilanBeneficesTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public BilanBeneficesTablePageData() {
  }

  @Override
  public BilanBeneficesTableRowData addRow() {
    return (BilanBeneficesTableRowData) super.addRow();
  }

  @Override
  public BilanBeneficesTableRowData addRow(int rowState) {
    return (BilanBeneficesTableRowData) super.addRow(rowState);
  }

  @Override
  public BilanBeneficesTableRowData createRow() {
    return new BilanBeneficesTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return BilanBeneficesTableRowData.class;
  }

  @Override
  public BilanBeneficesTableRowData[] getRows() {
    return (BilanBeneficesTableRowData[]) super.getRows();
  }

  @Override
  public BilanBeneficesTableRowData rowAt(int index) {
    return (BilanBeneficesTableRowData) super.rowAt(index);
  }

  public void setRows(BilanBeneficesTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class BilanBeneficesTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String debitParOperation = "debitParOperation";
    public static final String dateEnvoi = "dateEnvoi";
    public static final String montantDebite = "montantDebite";
    public static final String envoyeA = "envoyeA";
    public static final String benefice = "benefice";
    private Long m_debitParOperation;
    private Date m_dateEnvoi;
    private BigDecimal m_montantDebite;
    private String m_envoyeA;
    private BigDecimal m_benefice;

    public BilanBeneficesTableRowData() {
    }

    /**
     * @return the DebitParOperation
     */
    public Long getDebitParOperation() {
      return m_debitParOperation;
    }

    /**
     * @param debitParOperation
     *          the DebitParOperation to set
     */
    public void setDebitParOperation(Long debitParOperation) {
      m_debitParOperation = debitParOperation;
    }

    /**
     * @return the DateEnvoi
     */
    public Date getDateEnvoi() {
      return m_dateEnvoi;
    }

    /**
     * @param dateEnvoi
     *          the DateEnvoi to set
     */
    public void setDateEnvoi(Date dateEnvoi) {
      m_dateEnvoi = dateEnvoi;
    }

    /**
     * @return the MontantDebite
     */
    public BigDecimal getMontantDebite() {
      return m_montantDebite;
    }

    /**
     * @param montantDebite
     *          the MontantDebite to set
     */
    public void setMontantDebite(BigDecimal montantDebite) {
      m_montantDebite = montantDebite;
    }

    /**
     * @return the EnvoyeA
     */
    public String getEnvoyeA() {
      return m_envoyeA;
    }

    /**
     * @param envoyeA
     *          the EnvoyeA to set
     */
    public void setEnvoyeA(String envoyeA) {
      m_envoyeA = envoyeA;
    }

    /**
     * @return the Benefice
     */
    public BigDecimal getBenefice() {
      return m_benefice;
    }

    /**
     * @param benefice
     *          the Benefice to set
     */
    public void setBenefice(BigDecimal benefice) {
      m_benefice = benefice;
    }
  }
}