/**
 * 
 */
package mg.alpha.gestion.operations.shared.ui.desktop.outlines.pages.forms.operations;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ComptesParticuliersFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public ComptesParticuliersFormData() {
  }

  public ComptesParticuliers getComptesParticuliers() {
    return getFieldByClass(ComptesParticuliers.class);
  }

  /**
   * access method for property ComptesParticuliersNr.
   */
  public Long getComptesParticuliersNr() {
    return getComptesParticuliersNrProperty().getValue();
  }

  /**
   * access method for property ComptesParticuliersNr.
   */
  public void setComptesParticuliersNr(Long comptesParticuliersNr) {
    getComptesParticuliersNrProperty().setValue(comptesParticuliersNr);
  }

  public ComptesParticuliersNrProperty getComptesParticuliersNrProperty() {
    return getPropertyByClass(ComptesParticuliersNrProperty.class);
  }

  /**
   * access method for property IdFromTimestamp.
   */
  public Long getIdFromTimestamp() {
    return getIdFromTimestampProperty().getValue();
  }

  /**
   * access method for property IdFromTimestamp.
   */
  public void setIdFromTimestamp(Long idFromTimestamp) {
    getIdFromTimestampProperty().setValue(idFromTimestamp);
  }

  public IdFromTimestampProperty getIdFromTimestampProperty() {
    return getPropertyByClass(IdFromTimestampProperty.class);
  }

  public static class ComptesParticuliers extends AbstractTableFieldBeanData {

    private static final long serialVersionUID = 1L;

    public ComptesParticuliers() {
    }

    @Override
    public ComptesParticuliersRowData addRow() {
      return (ComptesParticuliersRowData) super.addRow();
    }

    @Override
    public ComptesParticuliersRowData addRow(int rowState) {
      return (ComptesParticuliersRowData) super.addRow(rowState);
    }

    @Override
    public ComptesParticuliersRowData createRow() {
      return new ComptesParticuliersRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return ComptesParticuliersRowData.class;
    }

    @Override
    public ComptesParticuliersRowData[] getRows() {
      return (ComptesParticuliersRowData[]) super.getRows();
    }

    @Override
    public ComptesParticuliersRowData rowAt(int index) {
      return (ComptesParticuliersRowData) super.rowAt(index);
    }

    public void setRows(ComptesParticuliersRowData[] rows) {
      super.setRows(rows);
    }

    public static class ComptesParticuliersRowData extends AbstractTableRowData {

      private static final long serialVersionUID = 1L;
      public static final String sommeParCompteId = "sommeParCompteId";
      public static final String compteParticulier = "compteParticulier";
      public static final String sommeEnvoyee = "sommeEnvoyee";
      private Long m_sommeParCompteId;
      private String m_compteParticulier;
      private BigInteger m_sommeEnvoyee;

      public ComptesParticuliersRowData() {
      }

      /**
       * @return the SommeParCompteId
       */
      public Long getSommeParCompteId() {
        return m_sommeParCompteId;
      }

      /**
       * @param sommeParCompteId
       *          the SommeParCompteId to set
       */
      public void setSommeParCompteId(Long sommeParCompteId) {
        m_sommeParCompteId = sommeParCompteId;
      }

      /**
       * @return the CompteParticulier
       */
      public String getCompteParticulier() {
        return m_compteParticulier;
      }

      /**
       * @param compteParticulier
       *          the CompteParticulier to set
       */
      public void setCompteParticulier(String compteParticulier) {
        m_compteParticulier = compteParticulier;
      }

      /**
       * @return the SommeEnvoyee
       */
      public BigInteger getSommeEnvoyee() {
        return m_sommeEnvoyee;
      }

      /**
       * @param sommeEnvoyee
       *          the SommeEnvoyee to set
       */
      public void setSommeEnvoyee(BigInteger sommeEnvoyee) {
        m_sommeEnvoyee = sommeEnvoyee;
      }
    }
  }

  public static class ComptesParticuliersNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public ComptesParticuliersNrProperty() {
    }
  }

  public static class IdFromTimestampProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public IdFromTimestampProperty() {
    }
  }
}