/**
 * 
 */
package mg.alpha.gestion.operations.shared.ui.desktop.outlines.pages.forms.operations;

import java.math.BigDecimal;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import mg.alpha.gestion.operations.shared.services.lookup.CompteParticulierLookupCall;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PartagerVersComptesParticuliersFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public PartagerVersComptesParticuliersFormData() {
  }

  public CompteParticulier getCompteParticulier() {
    return getFieldByClass(CompteParticulier.class);
  }

  /**
   * access method for property CreationTimestamp.
   */
  public Long getCreationTimestamp() {
    return getCreationTimestampProperty().getValue();
  }

  /**
   * access method for property CreationTimestamp.
   */
  public void setCreationTimestamp(Long creationTimestamp) {
    getCreationTimestampProperty().setValue(creationTimestamp);
  }

  public CreationTimestampProperty getCreationTimestampProperty() {
    return getPropertyByClass(CreationTimestampProperty.class);
  }

  /**
   * access method for property PartagerVersComptesParticuliersNr.
   */
  public Long getPartagerVersComptesParticuliersNr() {
    return getPartagerVersComptesParticuliersNrProperty().getValue();
  }

  /**
   * access method for property PartagerVersComptesParticuliersNr.
   */
  public void setPartagerVersComptesParticuliersNr(Long partagerVersComptesParticuliersNr) {
    getPartagerVersComptesParticuliersNrProperty().setValue(partagerVersComptesParticuliersNr);
  }

  public PartagerVersComptesParticuliersNrProperty getPartagerVersComptesParticuliersNrProperty() {
    return getPropertyByClass(PartagerVersComptesParticuliersNrProperty.class);
  }

  public SommeAEnvoyer getSommeAEnvoyer() {
    return getFieldByClass(SommeAEnvoyer.class);
  }

  public VousPouvezPartager getVousPouvezPartager() {
    return getFieldByClass(VousPouvezPartager.class);
  }

  public static class CompteParticulier extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;

    public CompteParticulier() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.LOOKUP_CALL, CompteParticulierLookupCall.class);
      ruleMap.put(ValidationRule.ZERO_NULL_EQUALITY, true);
    }
  }

  public static class CreationTimestampProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public CreationTimestampProperty() {
    }
  }

  public static class PartagerVersComptesParticuliersNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public PartagerVersComptesParticuliersNrProperty() {
    }
  }

  public static class SommeAEnvoyer extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;

    public SommeAEnvoyer() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, new BigDecimal("999999999999999999999999999999999999999999999999999999999999"));
      ruleMap.put(ValidationRule.MIN_VALUE, new BigDecimal("-999999999999999999999999999999999999999999999999999999999999"));
    }
  }

  public static class VousPouvezPartager extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;

    public VousPouvezPartager() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, new BigDecimal("999999999999999999999999999999999999999999999999999999999999"));
      ruleMap.put(ValidationRule.MIN_VALUE, new BigDecimal("-999999999999999999999999999999999999999999999999999999999999"));
    }
  }
}