/**
 * 
 */
package mg.alpha.gestion.operations.shared.ui.desktop.outlines.pages.forms.bilan;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class BilanBeneficesSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public BilanBeneficesSearchFormData() {
  }

  public Benefice getBenefice() {
    return getFieldByClass(Benefice.class);
  }

  public DateEnvoiFrom getDateEnvoiFrom() {
    return getFieldByClass(DateEnvoiFrom.class);
  }

  public DateEnvoiTo getDateEnvoiTo() {
    return getFieldByClass(DateEnvoiTo.class);
  }

  public EnvoyeA getEnvoyeA() {
    return getFieldByClass(EnvoyeA.class);
  }

  public MontantDebite getMontantDebite() {
    return getFieldByClass(MontantDebite.class);
  }

  public static class Benefice extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;

    public Benefice() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, new BigDecimal("999999999999999999999999999999999999999999999999999999999999"));
      ruleMap.put(ValidationRule.MIN_VALUE, new BigDecimal("-999999999999999999999999999999999999999999999999999999999999"));
    }
  }

  public static class DateEnvoiFrom extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public DateEnvoiFrom() {
    }
  }

  public static class DateEnvoiTo extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public DateEnvoiTo() {
    }
  }

  public static class EnvoyeA extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public EnvoyeA() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class MontantDebite extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;

    public MontantDebite() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, new BigDecimal("999999999999999999999999999999999999999999999999999999999999"));
      ruleMap.put(ValidationRule.MIN_VALUE, new BigDecimal("-999999999999999999999999999999999999999999999999999999999999"));
    }
  }
}