/**
 * 
 */
package mg.alpha.gestion.operations.shared.ui.desktop.outlines;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ComptesParticuliersTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public ComptesParticuliersTablePageData() {
  }

  @Override
  public ComptesParticuliersTableRowData addRow() {
    return (ComptesParticuliersTableRowData) super.addRow();
  }

  @Override
  public ComptesParticuliersTableRowData addRow(int rowState) {
    return (ComptesParticuliersTableRowData) super.addRow(rowState);
  }

  @Override
  public ComptesParticuliersTableRowData createRow() {
    return new ComptesParticuliersTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return ComptesParticuliersTableRowData.class;
  }

  @Override
  public ComptesParticuliersTableRowData[] getRows() {
    return (ComptesParticuliersTableRowData[]) super.getRows();
  }

  @Override
  public ComptesParticuliersTableRowData rowAt(int index) {
    return (ComptesParticuliersTableRowData) super.rowAt(index);
  }

  public void setRows(ComptesParticuliersTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class ComptesParticuliersTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String sommeParCompteParticulierId = "sommeParCompteParticulierId";
    public static final String compteParticulier = "compteParticulier";
    public static final String compteDenvoi = "compteDenvoi";
    public static final String montantEnvoye = "montantEnvoye";
    public static final String prixDeVenteUnite = "prixDeVenteUnite";
    public static final String dateEnvoi = "dateEnvoi";
    public static final String timestamp = "timestamp";
    public static final String commentaire = "commentaire";
    private Long m_sommeParCompteParticulierId;
    private String m_compteParticulier;
    private String m_compteDenvoi;
    private BigDecimal m_montantEnvoye;
    private BigDecimal m_prixDeVenteUnite;
    private Date m_dateEnvoi;
    private Long m_timestamp;
    private String m_commentaire;

    public ComptesParticuliersTableRowData() {
    }

    /**
     * @return the SommeParCompteParticulierId
     */
    public Long getSommeParCompteParticulierId() {
      return m_sommeParCompteParticulierId;
    }

    /**
     * @param sommeParCompteParticulierId
     *          the SommeParCompteParticulierId to set
     */
    public void setSommeParCompteParticulierId(Long sommeParCompteParticulierId) {
      m_sommeParCompteParticulierId = sommeParCompteParticulierId;
    }

    /**
     * @return the CompteParticulier
     */
    public String getCompteParticulier() {
      return m_compteParticulier;
    }

    /**
     * @param compteParticulier
     *          the CompteParticulier to set
     */
    public void setCompteParticulier(String compteParticulier) {
      m_compteParticulier = compteParticulier;
    }

    /**
     * @return the CompteDenvoi
     */
    public String getCompteDenvoi() {
      return m_compteDenvoi;
    }

    /**
     * @param compteDenvoi
     *          the CompteDenvoi to set
     */
    public void setCompteDenvoi(String compteDenvoi) {
      m_compteDenvoi = compteDenvoi;
    }

    /**
     * @return the MontantEnvoye
     */
    public BigDecimal getMontantEnvoye() {
      return m_montantEnvoye;
    }

    /**
     * @param montantEnvoye
     *          the MontantEnvoye to set
     */
    public void setMontantEnvoye(BigDecimal montantEnvoye) {
      m_montantEnvoye = montantEnvoye;
    }

    /**
     * @return the PrixDeVenteUnite
     */
    public BigDecimal getPrixDeVenteUnite() {
      return m_prixDeVenteUnite;
    }

    /**
     * @param prixDeVenteUnite
     *          the PrixDeVenteUnite to set
     */
    public void setPrixDeVenteUnite(BigDecimal prixDeVenteUnite) {
      m_prixDeVenteUnite = prixDeVenteUnite;
    }

    /**
     * @return the DateEnvoi
     */
    public Date getDateEnvoi() {
      return m_dateEnvoi;
    }

    /**
     * @param dateEnvoi
     *          the DateEnvoi to set
     */
    public void setDateEnvoi(Date dateEnvoi) {
      m_dateEnvoi = dateEnvoi;
    }

    /**
     * @return the Timestamp
     */
    public Long getTimestamp() {
      return m_timestamp;
    }

    /**
     * @param timestamp
     *          the Timestamp to set
     */
    public void setTimestamp(Long timestamp) {
      m_timestamp = timestamp;
    }

    /**
     * @return the Commentaire
     */
    public String getCommentaire() {
      return m_commentaire;
    }

    /**
     * @param commentaire
     *          the Commentaire to set
     */
    public void setCommentaire(String commentaire) {
      m_commentaire = commentaire;
    }
  }
}