/**
 * 
 */
package mg.alpha.gestion.operations.shared.ui.desktop.outlines;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ComptesParticuliersSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public ComptesParticuliersSearchFormData() {
  }

  public CompteDenvoi getCompteDenvoi() {
    return getFieldByClass(CompteDenvoi.class);
  }

  public CompteParticulier getCompteParticulier() {
    return getFieldByClass(CompteParticulier.class);
  }

  public DateEnvoiFrom getDateEnvoiFrom() {
    return getFieldByClass(DateEnvoiFrom.class);
  }

  public DateEnvoiTo getDateEnvoiTo() {
    return getFieldByClass(DateEnvoiTo.class);
  }

  public MontantEnvoye getMontantEnvoye() {
    return getFieldByClass(MontantEnvoye.class);
  }

  public PrixDeVenteUnite getPrixDeVenteUnite() {
    return getFieldByClass(PrixDeVenteUnite.class);
  }

  public static class CompteDenvoi extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public CompteDenvoi() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class CompteParticulier extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public CompteParticulier() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class DateEnvoiFrom extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public DateEnvoiFrom() {
    }
  }

  public static class DateEnvoiTo extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;

    public DateEnvoiTo() {
    }
  }

  public static class MontantEnvoye extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;

    public MontantEnvoye() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, new BigDecimal("999999999999999999999999999999999999999999999999999999999999"));
      ruleMap.put(ValidationRule.MIN_VALUE, new BigDecimal("-999999999999999999999999999999999999999999999999999999999999"));
    }
  }

  public static class PrixDeVenteUnite extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;

    public PrixDeVenteUnite() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_VALUE, new BigDecimal("999999999999999999999999999999999999999999999999999999999999"));
      ruleMap.put(ValidationRule.MIN_VALUE, new BigDecimal("-999999999999999999999999999999999999999999999999999999999999"));
    }
  }
}